ssh2.c

Currently, `ssh2` function does not support reflection API.
So, it's not possible to retrieve theirs parameters and it's a problem in unit tests (for example) because it's not possible to mock correctly these functions and assert on them efficiently.
So, this PR add reflection API support, so it's now possible to do:
```php
fch@Mageekbook:~/Pecl/Ssh2(master *)
26> php -a
Interactive shell
php > $f = new reflectionFunction('ssh2_exec');
php > var_dump($f->getParameters());
array(7) {
[0]=>
&object(ReflectionParameter)#2 (1) {
["name"]=>
string(7) "session"
}
[1]=>
&object(ReflectionParameter)#3 (1) {
["name"]=>
string(7) "command"
}
[2]=>
&object(ReflectionParameter)#4 (1) {
["name"]=>
string(3) "pty"
}
[3]=>
&object(ReflectionParameter)#5 (1) {
["name"]=>
string(3) "env"
}
[4]=> …
```

Add reflection API support.

---

ssh2_fopen_wrappers.c

We need to set session to blocking mode before calling libssh2_channel_open_session().
This fixes long standing issue of ssh2_exec() failing with 'Unable to request a channel from remote host' when invoked for second time using same session. - https://bugs.php.net/bug.php?id=58893
ssh2_shell() has same construct, so same approach is applied there too.

Fix for ssh2_exec(): Unable to request a channel from remote host

---

.gitignore
php_ssh2.h
ssh2.c
ssh2_fopen_wrappers.c
ssh2_sftp.c

Hi!
This is a WIP branch for PHP 7 support. Currently all tests pass, but I still have some memory leaks I haven't addressed yet. I also need to mark a few spots that I have questions on. Would love some eyes on this to catch issues early on, thank you!
After that I am going to take swing fixing all the issues that show up with -Wall

PHP 7 Support 

---

config.w32

Win32 builds will now successfully link.
Expanded if statements to specify which library is missing rather than a generic one.

Made win32 builds depend on zlib and openssl extensions

---

ssh2_fopen_wrappers.c

This fixes ssh2_tunnel always failing to request a channel because libssh2_channel_direct_tcpip "Would block".

Add blocking call to php_ssh2_direct_tcpip

---

ssh2_fopen_wrappers.c

I reported a bug on the tracking site: https://bugs.php.net/bug.php?id=72150
This PR applies the patch proposed by @krakjoe, credits to him!

Fixing segfault when passing env variables

---

ssh2.c

This PR fix checking resource type in ssh2_pool. Bug in introduced by commit https://github.com/php/pecl-networking-ssh2/commit/452db3620c8d9d96f477c3c72181561228346e5a for PHP 7 compatibility.

fix checking resource type

---

ssh2_fopen_wrappers.c

This PR returns raising errors. Removed by commit https://github.com/php/pecl-networking-ssh2/commit/f028e8a3710a7a9a1b1e05ceb7790243e11ec4b4.

catching last error

---

ssh2_fopen_wrappers.c

This PR fixed returing psftp_rsrcid value, is needed returning handle from resource. Bug introduced by commit https://github.com/php/pecl-networking-ssh2/commit/d630c5eccae783a7858f00b362b775c0417b56eb.

fix returing psftp_rsrcid value

---

php_ssh2.h
ssh2.c
ssh2_fopen_wrappers.c
ssh2_sftp.c

This PR removing PHP 5 compatibility code in master branch.

Cleanup PHP 5 compatibility code in master branch

---

php_ssh2.h
ssh2.c
ssh2_fopen_wrappers.c
ssh2_sftp.c

This PR removing obsolete TSRMLS code for PHP 7 in master.

Cleanup obsolete TSRMLS in master

---

php_ssh2.h
ssh2.c
ssh2_fopen_wrappers.c
tests/ssh2_shell.phpt

1. php_ssh2_shell_open() was calling zend_hash_get_current_key_ex
2. php_ssh2_exec_command() / php_ssh2_shell_open() / php_ssh2_direct_tcpip()
were being passed a pointer instead of the resource ID.
3. Renamed session_rsrc to session_rsrcid
3. Added test for ssh2_shell and reading / writing to the stream

BUG_73819: call ssh2_shell() causes segment fault

---

.travis.yml
.travis/build.sh

This PR will allow automated testing with Travis CI. 
If an admin for this repo just enables TravisCI, automated testing will occur on merges and PRs.
Here is an example of a successful run from my repo:
https://travis-ci.org/mhagstrand/pecl-networking-ssh2/builds/199552224

Adding Travis CI to pecl-networking-ssh2

---

ssh2.c
ssh2_fopen_wrappers.c
ssh2_sftp.c

Multiple reflection or documentation disparities fixed:
* ssh2_connect
* added missing parameters
* only first parameter is required
* ssh2_disconnect
* renamed reflection parameter according to doc & other functions
* ssh2_methods_negotiated
* renamed reflection parameter according to doc & other functions
* ssh2_fingerprint
* renamed reflection parameter according to doc & other functions
* second parameter is optional
* ssh2_scp_send
* swap parameters according to docs
* ssh2_fetch_stream
* rename reflection parameter according to docs
* ssh2_sftp_mkdir
* sync parameter & variable name according to docs
* ssh2_sftp_rmdir
* sync parameter & variable name according to docs

Fix multiple reflection/documentation disparities

---

.travis.yml
ssh2_sftp.c

That were fixed in https://github.com/php/pecl-networking-ssh2/commit/073067ba96ac99ed5696d27f13ca6c8124986e74#diff-d0296647d3a59f029c56a9154f65ab01R52
But this inline still causing build issues
PS: related to https://github.com/alpinelinux/aports/pull/6226 and http://clang.llvm.org/compatibility.html#inline

Remove inline from php_ssh2_sftp_attr2ssb

---

ssh2_fopen_wrappers.c
tests/ssh2_stream_select.phpt

PHP streams provide access to the select() system call via stream_select() for streams which can be cast as socket and/or file descriptors. This change implements the cast function provided to PHP stream resources representing SSH2 shell sessions, or those obtained via ssh2_shell. 
The cast funtion simply yields the socket established during ssh2_connect for the purposes of enabling PHP's stream_select() to indicate read readiness on the SSH2 shell stream. Note that data available on the socket does not necessarily indicate data available on the shell stream's underlying LIBSSH2_CHANNEL object, as protocol data is filtered. Callers must be aware that no data may be available to read on the shell stream despite positive indication from stream_select(). The rate of such false positives is …

Adding support for stream_select to shell streams

---

ssh2.c

Update public key authentication to avoid data corruption potential

---

package.xml
php_ssh2.h
ssh2.c
ssh2_fopen_wrappers.c
tests/ssh2_send_eof.phpt

Without this, you can't close the standard input stream without also closing the standard output stream. One can try to redirect
standard output to error, but having a reference on the error stream keeps a reference on the stdio stream, so closing stdio
won't decrement the reference count enough to actually close the stream.
This makes it possible to use programs over SSH that take their input over standard input without any temporary files/redirection, and get the output back over standard output.

Add ssh2_send_eof function

---

ssh2_fopen_wrappers.c
ssh2_sftp.c

fixed segfaults connecting to not existing host or trying to acess file with file_get_contents()
As mentioned [here](https://github.com/php/php-src/pull/5980) not sending unitialized variable to zend_list_delete

Bug #79757 segfaults

---

ssh2_sftp.c
tests/bug79631.phpt

If the SSH2 Session resource has already been closed, the libssh2
session has been as well, and the `LIBSSH2_SESSION*` has been set NULL.
If that is the case, we must not call `libssh2_sftp_shutdown()`.
---
Note that this patch only resolves the particular shutdown issue, but does not generally address using the SSH2 SFTP resource after the SSH2 Session resource has been closed (i.e. calling any of the `ssh2_sftp_*()` functions after `ssh2_disconnect($ssh)` still segfaults).  This would have to be handled for every `ssh2_sftp_*()` function individually.  If you like, I can amend this PR respectively, or submit another PR. But maybe there is a more elegant solution I'm missing?

Fix #79631: SSH disconnect segfault with SFTP (assertion failed)

---

ssh2_fopen_wrappers.c
tests/bug63480.phpt

There is no need to warn if an SSH2 Session resource is given, so we
suppress the potential warning by passing NULL as `resource_type_name`.

Fix #63480: Warning on using the SSH2 Session resource in the uri

---

ssh2_fopen_wrappers.c

We need to properly initialize the SSH2 Session resource.

Fix #80294: ssh2 wrappers not using an allocated resource segfault

---

config.w32

Obviously, the appropriate define is not done in config.w32, although
libssh2 1.4.2 is available for Windows builds as of 2012-09-20.  For
current PHP versions libssh2 1.9.0 is used on Windows.

Fix #75523: stream_set_timeout(): No support for ssh2 stream timeout

---

tests/ssh2_send_eof.phpt
tests/ssh2_stream_select.phpt

This test case executes `cat` and uses `PHP_EOL` as line ending.  This
causes the test to fail when executed on Windows connected to a Linux
SSH server.  Since `cat` is usually not available on Windows, running
the test would fail if a Windows SSH server was used.  Thus, we can
easily fix this by always using LF.

Fix line ending in test case when running on Windows

---

php_ssh2.h
ssh2_fopen_wrappers.c

On Windows, the socket type is not an `int` but rather `SOCKET` which
is actually `unsigned int` on x86 and `unsigned __int64` on x64.  To
cater to this type mismatch, PHP offers the portable `php_socket_t` (at
least as of PHP 5.0.0).  We use it for `php_ssh2_session_data` as well.
---
Note that this patch constitutes an ABI break, and as such likely needs to be postponed to the next major version. :(

Fix #80729: ssh2_shell() streams are not stream_select()able

---

ssh2_sftp.c

On [release 1.4](https://pecl.php.net/package-info.php?package=ssh2&version=1.4), we got warnings for implicit fallthroughs:
```
/builds/php/ext/ssh2/ssh2_sftp.c:172:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
172 |   {
|   ^
/builds/php/ext/ssh2/ssh2_sftp.c:183:3: note: here
183 |   case SEEK_CUR:
|   ^~~~
```
([permalink](https://github.com/php/pecl-networking-ssh2/blob/520e1f0810f226c7ea0290b9b3db77242d96157c/ssh2_sftp.c#L170-L193))

ssh2_sftp: remove implicit switch-case fallthrough in stream_seek

---

ssh2.c

This prevents a compile-time warning about missing field initializations. It's also consistent with the use of `PHP_FE` (internally alias of `ZEND_FE`)

End zend_function_entry ssh2_functions list with PHP_FE_END
